type: entities
title: Edmonton Alerts
entities:
  - type: conditional
    conditions:
      - entity: sensor.edmonton_warnings
        state: "1"
    row:
      entity: sensor.edmonton_warnings
      type: attribute
      name: " "
      secondary_info: last-changed
      attribute: alert_1
      icon: mdi:lightning-bolt
      tap_action:
        action: url
        url_path: https://weather.gc.ca/warnings/report_e.html?ab33=
  - type: conditional
    conditions:
      - entity: sensor.edmonton_watches
        state: "1"
    row:
      entity: sensor.edmonton_watches
      type: attribute
      attribute: alert_1
      icon: mdi:lightning-bolt
      name: " "
      secondary_info: last-changed
      tap_action:
        action: url
        url_path: https://weather.gc.ca/warnings/report_e.html?ab33=
  - type: conditional
    conditions:
      - entity: sensor.edmonton_watches
        state: "0"
      - entity: sensor.edmonton_warnings
        state: "0"
      - entity: sensor.edmonton_statements
        state: "0"
    row:
      type: attribute
      entity: input_text.no_alerts
      attribute: text1
      icon: none
      name: No alerts
  - type: conditional
    conditions:
      - entity: sensor.edmonton_statements
        state: "1"
    row:
      type: attribute
      entity: sensor.edmonton_statements
      attribute: alert_1
      icon: mdi:cloud-alert
      name: " "
      secondary_info: last-changed
      tap_action:
        action: url
        url_path: https://weather.gc.ca/warnings/report_e.html?ab33=
